### ISSUE TITLE
CircuitPython throws a syntax error on line 428 of rf24.py

### ISSUE THREAD

**Issue by jerryneedell** [nRF24/CircuitPython_nRF24L01#40]
I tried executing the nrf24l01_simple_test.py on a feather m4 express running both CircuitpYhton 7.3.0 and 8.0 alpha.1
and I get a syntax error on line 428 of rf24.py

https://github.com/nRF24/CircuitPython_nRF24L01/blob/master/circuitpython_nrf24l01/rf24.py#L428

simply adding a comma to line 427 fixes the problem
changing
```
print(
            f"Auto retry delay__________"
            f"{((self._retry_setup & 0xF0) >> 4) * 250 + 250} microseconds",
        )
```
to
```
print(
            f"Auto retry delay__________",
            f"{((self._retry_setup & 0xF0) >> 4) * 250 + 250} microseconds",
        )
```
resolves the issue on the feather m4 express.

The library runs OK as is on a Raspberry Pi.

**Comment by jerryneedell** [comment]
Using a + instead of a comma may be preferred -- the comma adds a space between the strings, the + concatenates.

**Comment by 2bndy5** [comment]
A `+` is preferable. I've been developing the next release on the no-more-upy branch, and I think this is already solved there (had some problems in cirPy v7.0 about using f-strs).

**Comment by 2bndy5** [comment]
Looks like I already reverted back to using 
https://github.com/nRF24/CircuitPython_nRF24L01/blob/43e9ae0de2f328faa4ef4e08f1488d4f7cc21cf9/circuitpython_nrf24l01/rf24.py#L443-L446
on my bleeding edge branch.

**Comment by jerryneedell** [comment]
Thanks for the quick response.

**Comment by 2bndy5** [comment]
Your feedback is always welcome. I'm just slow to release (for HW testing reasons).

**Comment by jerryneedell** [comment]
FYI -- I updated to the new release and ran the simple_ test between a Pi (3B+) and a Feather M4 Express running CP 8.0 alpha.1  -- worked fine!  Thanks

**Comment by 2bndy5** [comment]
I just finished testing all the examples on my Feather RP2040 (w/ CirPy v7.3.0) and my RPi4. Thus, the release.
